name: Deploy Paper

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write
  deployments: write

jobs:
  deploy:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: impact-scholars/isp-actions-config/.github/workflows/build-and-deploy.yml@feat/pr-preview
    with:
      base_url: /${{ github.event.repository.name }}

  preview:
    if: github.event_name == 'pull_request'
    uses: impact-scholars/isp-actions-config/.github/workflows/build-and-deploy.yml@feat/pr-preview
    with:
      target: cloudflare
      base_url: /
    secrets: inherit
